<?php
declare(strict_types=1);

return [
    // Button — https://daisyui.com/components/button/
    'button.base' => 'btn',
    'button.color.neutral' => 'btn-neutral',
    'button.color.primary' => 'btn-primary',
    'button.color.secondary' => 'btn-secondary',
    'button.color.accent' => 'btn-accent',
    'button.color.info' => 'btn-info',
    'button.color.success' => 'btn-success',
    'button.color.warning' => 'btn-warning',
    'button.color.error' => 'btn-error',
    'button.appearance.outline' => 'btn-outline',
    'button.appearance.dash' => 'btn-dash',
    'button.appearance.soft' => 'btn-soft',
    'button.appearance.ghost' => 'btn-ghost',
    'button.appearance.link' => 'btn-link',
    'button.behavior.active' => 'btn-active',
    'button.behavior.disabled' => 'btn-disabled',
    'button.size.xs' => 'btn-xs',
    'button.size.sm' => 'btn-sm',
    'button.size.md' => 'btn-md',
    'button.size.lg' => 'btn-lg',
    'button.size.xl' => 'btn-xl',
    'button.modifier.wide' => 'btn-wide',
    'button.modifier.block' => 'btn-block',
    'button.modifier.square' => 'btn-square',
    'button.modifier.circle' => 'btn-circle',

    // Badge — https://daisyui.com/components/badge/
    'badge.base' => 'badge',
    'badge.color.neutral' => 'badge-neutral',
    'badge.color.primary' => 'badge-primary',
    'badge.color.secondary' => 'badge-secondary',
    'badge.color.accent' => 'badge-accent',
    'badge.color.info' => 'badge-info',
    'badge.color.success' => 'badge-success',
    'badge.color.warning' => 'badge-warning',
    'badge.color.error' => 'badge-error',
    'badge.appearance.outline' => 'badge-outline',
    'badge.appearance.dash' => 'badge-dash',
    'badge.appearance.soft' => 'badge-soft',
    'badge.appearance.ghost' => 'badge-ghost',
    'badge.size.xs' => 'badge-xs',
    'badge.size.sm' => 'badge-sm',
    'badge.size.md' => 'badge-md',
    'badge.size.lg' => 'badge-lg',
    'badge.size.xl' => 'badge-xl',

    // Alert — https://daisyui.com/components/alert/
    'alert.base' => 'alert',
    'alert.color.info' => 'alert-info',
    'alert.color.success' => 'alert-success',
    'alert.color.warning' => 'alert-warning',
    'alert.color.error' => 'alert-error',
    'alert.appearance.outline' => 'alert-outline',
    'alert.appearance.dash' => 'alert-dash',
    'alert.appearance.soft' => 'alert-soft',
    'alert.direction.vertical' => 'alert-vertical',
    'alert.direction.horizontal' => 'alert-horizontal',
];
